application: web592group22
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(js|css|html|gif|png|jpg|js|css|svg|eot|ttf|woff|woff2))$
  static_files: \1
  upload: .*\.(js|css|html|gif|png|jpg|svg)$
  

- url: /(.*\.php)$
  script: \1

 

- url: .*
  script: main.php
